project_id = "lifecraftonline"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.tick-extraction]
verify_jwt = false

[functions.tick-manufacturing]
verify_jwt = false

[functions.tick-npc-purchases]
verify_jwt = false

[functions.tick-shipping]
verify_jwt = false

[functions.tick-travel]
verify_jwt = false

[functions.tick-wages]
verify_jwt = false
