import type { BusinessType } from "./businesses";

export const UPGRADE_EFFECT_KINDS = [
  "multiplier",
  "reduction_multiplier",
  "flat_slots",
  "flat_quality",
  "price_tolerance",
  "traffic_multiplier",
  "conversion_multiplier",
] as const;

export type UpgradeEffectKind = (typeof UPGRADE_EFFECT_KINDS)[number];

export const UPGRADE_FAMILIES = [
  "extraction",
  "capacity",
  "durability",
  "quality",
  "manufacturing",
  "store",
] as const;

export type UpgradeFamily = (typeof UPGRADE_FAMILIES)[number];

export const UPGRADE_PROJECT_CATEGORIES = [
  "equipment",
  "facility",
  "systems",
  "staffing",
  "storefront",
] as const;

export type UpgradeProjectCategory = (typeof UPGRADE_PROJECT_CATEGORIES)[number];

export const UPGRADE_STAGES = ["early", "mid", "late", "specialization"] as const;
export type UpgradeStage = (typeof UPGRADE_STAGES)[number];

export const UPGRADE_UI_FORMATS = [
  "percent_up",
  "percent_down",
  "flat_integer",
  "quality_points",
] as const;

export type UpgradeUiFormat = (typeof UPGRADE_UI_FORMATS)[number];

export const UPGRADE_DOWNTIME_POLICIES = ["none", "partial", "full"] as const;
export type UpgradeDowntimePolicy = (typeof UPGRADE_DOWNTIME_POLICIES)[number];

export type UpgradePrerequisite = {
  upgradeKey: BusinessUpgradeKey;
  minLevel: number;
};

export type BusinessUpgradeDefinition = {
  key: BusinessUpgradeKey;
  family: UpgradeFamily;
  displayName: string;
  shortDescription: string;
  immersiveLabel: string;
  projectCategory: UpgradeProjectCategory;
  appliesTo: readonly BusinessType[];
  effectKind: UpgradeEffectKind;
  baseCost: number;
  costMultiplier: number;
  baseEffect: number;
  gainMultiplier: number;
  installTimeMinutes: number;
  downtimePolicy: UpgradeDowntimePolicy;
  stage: UpgradeStage;
  maxLevel: number | null;
  isInfinite: boolean;
  uiFormat: UpgradeUiFormat;
  effectLabel: string;
  prerequisites?: UpgradePrerequisite[];
  mutuallyExclusiveWith?: BusinessUpgradeKey[];
  isSpecialization?: boolean;
};

export const BUSINESS_UPGRADE_KEYS = [
  // --- SHARED / CROSS-BUSINESS ---
  "extraction_efficiency",
  "worker_capacity",
  "tool_durability",
  "ore_quality",
  "crop_yield",
  "water_efficiency",
  "production_efficiency",
  "equipment_quality",
  "storefront_appeal",
  "listing_capacity",
  "customer_service",
  // --- MINE ---
  "mine_survey_crew",
  "mine_shaft_rails",
  "mine_blasting_permits",
  "mine_ventilation_system",
  "mine_ore_sorting_deck",
  "mine_shaft_deepening",
  "mine_open_pit_conversion",
  "mine_refined_tunneling",
  // --- FARM ---
  "farm_seed_stock",
  "farm_compost_system",
  "farm_drip_irrigation",
  "farm_grain_silo",
  "farm_greenhouse",
  "farm_combine_harvester",
  "farm_organic_certification",
  "farm_industrial_scale",
  // --- LOGGING CAMP ---
  "logging_chainsaw_fleet",
  "logging_skid_road",
  "logging_loader_crane",
  "logging_reforestation",
  "logging_bunkhouse",
  "logging_log_processor",
  "logging_sustainable_cert",
  "logging_clear_cut",
  // --- OIL WELL ---
  "oil_pump_jack",
  "oil_separator_tank",
  "oil_secondary_recovery",
  "oil_pipeline_connection",
  "oil_tertiary_recovery",
  "oil_refinery_stub",
  "oil_scada_automation",
  "oil_manual_optimization",
  // --- WATER COMPANY ---
  "water_filter_upgrade",
  "water_pressure_system",
  "water_reservoir_expansion",
  "water_treatment_plant",
  "water_distribution_network",
  "water_automated_monitoring",
  "water_community_focus",
  // --- SAWMILL ---
  "sawmill_blade_set",
  "sawmill_log_deck",
  "sawmill_kiln_dryer",
  "sawmill_planer_mill",
  "sawmill_waste_boiler",
  "sawmill_cnc_router",
  "sawmill_mass_production",
  "sawmill_premium_lumber",
  // --- METALWORKING FACTORY ---
  "metal_forge_lining",
  "metal_grinder_rack",
  "metal_induction_furnace",
  "metal_cnc_lathe",
  "metal_heat_treatment_oven",
  "metal_robotic_welder",
  "metal_specialty_alloys",
  "metal_mass_stampings",
  // --- FOOD PROCESSING PLANT ---
  "food_cold_storage",
  "food_pasteurizer",
  "food_packaging_line",
  "food_batch_cooker",
  "food_freeze_dryer",
  "food_organic_label",
  "food_mass_market",
  // --- WINERY / DISTILLERY ---
  "winery_oak_barrels",
  "winery_grape_press",
  "winery_temperature_tanks",
  "winery_bottling_line",
  "winery_cellar_expansion",
  "winery_master_distiller",
  "winery_prestige_label",
  "winery_bulk_distribution",
  // --- CARPENTRY WORKSHOP ---
  "carp_hand_tool_set",
  "carp_table_saw",
  "carp_dust_collector",
  "carp_spray_booth",
  "carp_panel_saw",
  "carp_cnc_joinery",
  "carp_bespoke_workshop",
  "carp_production_shop",
  // --- GENERAL STORE ---
  "store_window_display",
  "store_loyalty_board",
  "store_pos_system",
  "store_stockroom_shelving",
  "store_delivery_van",
  "store_second_checkout",
  "store_franchise_model",
  "store_premium_boutique",
  // --- SPECIALTY STORE ---
  "spec_expert_staff",
  "spec_display_case",
  "spec_private_label",
  "spec_loyalty_program",
  "spec_event_space",
  "spec_membership_tier",
  "spec_exclusive_supplier",
  "spec_flagship_store",
] as const;

export type BusinessUpgradeKey = (typeof BUSINESS_UPGRADE_KEYS)[number];

export const BUSINESS_UPGRADE_DEFINITIONS: Record<BusinessUpgradeKey, BusinessUpgradeDefinition> = {

  // ─── SHARED / CROSS-BUSINESS ────────────────────────────────────────────────

  extraction_efficiency: {
    key: "extraction_efficiency",
    family: "extraction",
    displayName: "Extraction Efficiency",
    shortDescription: "Improves extraction output per minute.",
    immersiveLabel: "Optimise flow routing, drill pacing, and load-out sequences.",
    projectCategory: "equipment",
    appliesTo: ["mine", "water_company", "logging_camp", "oil_well"],
    effectKind: "multiplier",
    baseCost: 500,
    costMultiplier: 1.35,
    baseEffect: 1.08,
    gainMultiplier: 1.05,
    installTimeMinutes: 45,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  worker_capacity: {
    key: "worker_capacity",
    family: "capacity",
    displayName: "Worker Capacity",
    shortDescription: "Adds production positions and floor capacity.",
    immersiveLabel: "Expand staging areas, lane access, and crew coverage across the site.",
    projectCategory: "facility",
    appliesTo: [
      "mine", "farm", "water_company", "logging_camp", "oil_well",
      "sawmill", "metalworking_factory", "food_processing_plant",
      "winery_distillery", "carpentry_workshop",
    ],
    effectKind: "flat_slots",
    baseCost: 2200,
    costMultiplier: 1.4,
    baseEffect: 1,
    gainMultiplier: 1.1,
    installTimeMinutes: 180,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: 6,
    isInfinite: false,
    uiFormat: "flat_integer",
    effectLabel: "Additional worker slots",
  },

  tool_durability: {
    key: "tool_durability",
    family: "durability",
    displayName: "Tool Durability",
    shortDescription: "Extends tool lifetime before breakage.",
    immersiveLabel: "Establish maintenance benches, harden bits, and enforce spare-part discipline.",
    projectCategory: "systems",
    appliesTo: ["mine", "logging_camp", "oil_well"],
    effectKind: "multiplier",
    baseCost: 800,
    costMultiplier: 1.35,
    baseEffect: 1.15,
    gainMultiplier: 1.04,
    installTimeMinutes: 60,
    downtimePolicy: "none",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Tool durability multiplier",
  },

  ore_quality: {
    key: "ore_quality",
    family: "quality",
    displayName: "Ore Quality",
    shortDescription: "Improves mined material quality.",
    immersiveLabel: "Upgrade the sorting deck and pursue deeper, richer seam selection.",
    projectCategory: "equipment",
    appliesTo: ["mine"],
    effectKind: "flat_quality",
    baseCost: 1300,
    costMultiplier: 1.35,
    baseEffect: 4,
    gainMultiplier: 1.1,
    installTimeMinutes: 90,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  crop_yield: {
    key: "crop_yield",
    family: "extraction",
    displayName: "Crop Yield",
    shortDescription: "Improves farm output per cycle.",
    immersiveLabel: "Refine irrigation timing, row spacing, and harvest scheduling.",
    projectCategory: "systems",
    appliesTo: ["farm"],
    effectKind: "multiplier",
    baseCost: 400,
    costMultiplier: 1.32,
    baseEffect: 1.08,
    gainMultiplier: 1.05,
    installTimeMinutes: 30,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  water_efficiency: {
    key: "water_efficiency",
    family: "durability",
    displayName: "Water Efficiency",
    shortDescription: "Reduces water consumed by the farm.",
    immersiveLabel: "Dig retention trenches, tune pump controls, and tighten irrigation discipline.",
    projectCategory: "systems",
    appliesTo: ["farm"],
    effectKind: "reduction_multiplier",
    baseCost: 500,
    costMultiplier: 1.35,
    baseEffect: 0.92,
    gainMultiplier: 1.08,
    installTimeMinutes: 45,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_down",
    effectLabel: "Water use multiplier",
  },

  production_efficiency: {
    key: "production_efficiency",
    family: "manufacturing",
    displayName: "Production Efficiency",
    shortDescription: "Increases manufacturing output quantity.",
    immersiveLabel: "Tune feed pacing, floor flow, and cycle timing for consistent throughput.",
    projectCategory: "equipment",
    appliesTo: [
      "sawmill", "metalworking_factory", "food_processing_plant",
      "winery_distillery", "carpentry_workshop",
    ],
    effectKind: "multiplier",
    baseCost: 1800,
    costMultiplier: 1.45,
    baseEffect: 1.15,
    gainMultiplier: 1.05,
    installTimeMinutes: 60,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  equipment_quality: {
    key: "equipment_quality",
    family: "quality",
    displayName: "Equipment Quality",
    shortDescription: "Raises output quality for manufacturing.",
    immersiveLabel: "Improve alignment, finish consistency, and tighten process tolerances.",
    projectCategory: "equipment",
    appliesTo: [
      "sawmill", "metalworking_factory", "food_processing_plant",
      "winery_distillery", "carpentry_workshop",
    ],
    effectKind: "flat_quality",
    baseCost: 1500,
    costMultiplier: 1.35,
    baseEffect: 5,
    gainMultiplier: 1.1,
    installTimeMinutes: 90,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  storefront_appeal: {
    key: "storefront_appeal",
    family: "store",
    displayName: "Storefront Appeal",
    shortDescription: "Increases NPC traffic to the store.",
    immersiveLabel: "Refresh the window display, improve signage, and clean up the exterior.",
    projectCategory: "storefront",
    appliesTo: ["general_store", "specialty_store"],
    effectKind: "traffic_multiplier",
    baseCost: 950,
    costMultiplier: 1.35,
    baseEffect: 1.05,
    gainMultiplier: 1.03,
    installTimeMinutes: 45,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Traffic multiplier",
  },

  listing_capacity: {
    key: "listing_capacity",
    family: "capacity",
    displayName: "Listing Capacity",
    shortDescription: "Adds more shelf and listing capacity.",
    immersiveLabel: "Install new shelving runs, route stockroom access, and tighten merchandising density.",
    projectCategory: "facility",
    appliesTo: ["general_store", "specialty_store"],
    effectKind: "flat_slots",
    baseCost: 1200,
    costMultiplier: 1.35,
    baseEffect: 1,
    gainMultiplier: 1.1,
    installTimeMinutes: 120,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: 10,
    isInfinite: false,
    uiFormat: "flat_integer",
    effectLabel: "Additional listings",
  },

  customer_service: {
    key: "customer_service",
    family: "store",
    displayName: "Customer Service",
    shortDescription: "Improves conversion and pricing resilience.",
    immersiveLabel: "Redesign counter layout, speed up checkout, and train floor staff on product knowledge.",
    projectCategory: "staffing",
    appliesTo: ["general_store", "specialty_store"],
    effectKind: "conversion_multiplier",
    baseCost: 1700,
    costMultiplier: 1.35,
    baseEffect: 1.03,
    gainMultiplier: 1.02,
    installTimeMinutes: 30,
    downtimePolicy: "none",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Conversion multiplier",
  },

  // ─── MINE ───────────────────────────────────────────────────────────────────

  mine_survey_crew: {
    key: "mine_survey_crew",
    family: "extraction",
    displayName: "Survey Crew",
    shortDescription: "A geologist locates richer seams and better dig angles.",
    immersiveLabel: "Hire a geological survey team to map veins and mark the highest-yield faces.",
    projectCategory: "staffing",
    appliesTo: ["mine"],
    effectKind: "multiplier",
    baseCost: 600,
    costMultiplier: 1.32,
    baseEffect: 1.08,
    gainMultiplier: 1.04,
    installTimeMinutes: 30,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  mine_shaft_rails: {
    key: "mine_shaft_rails",
    family: "extraction",
    displayName: "Shaft Cart Rails",
    shortDescription: "Replace hand-carry with ore carts on steel rails.",
    immersiveLabel: "Lay steel rail tracks down each shaft so ore carts replace bucket-and-rope haulage.",
    projectCategory: "facility",
    appliesTo: ["mine"],
    effectKind: "multiplier",
    baseCost: 1400,
    costMultiplier: 1.35,
    baseEffect: 1.10,
    gainMultiplier: 1.04,
    installTimeMinutes: 120,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "mine_survey_crew", minLevel: 1 }],
  },

  mine_blasting_permits: {
    key: "mine_blasting_permits",
    family: "extraction",
    displayName: "Blasting Permits",
    shortDescription: "Licensed explosives access breaks rock far faster than picks.",
    immersiveLabel: "Acquire demolition licenses, set up a powder magazine, and train a shot-firer crew.",
    projectCategory: "systems",
    appliesTo: ["mine"],
    effectKind: "multiplier",
    baseCost: 4500,
    costMultiplier: 1.40,
    baseEffect: 1.18,
    gainMultiplier: 1.05,
    installTimeMinutes: 240,
    downtimePolicy: "full",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "mine_shaft_rails", minLevel: 2 }],
  },

  mine_ventilation_system: {
    key: "mine_ventilation_system",
    family: "extraction",
    displayName: "Ventilation System",
    shortDescription: "Airflow system allows deeper and safer shaft work.",
    immersiveLabel: "Install main fans, ducting, and fresh-air circuits so crews can work deeper faces.",
    projectCategory: "facility",
    appliesTo: ["mine"],
    effectKind: "multiplier",
    baseCost: 8000,
    costMultiplier: 1.42,
    baseEffect: 1.12,
    gainMultiplier: 1.05,
    installTimeMinutes: 360,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [
      { upgradeKey: "worker_capacity", minLevel: 2 },
      { upgradeKey: "mine_blasting_permits", minLevel: 1 },
    ],
  },

  mine_ore_sorting_deck: {
    key: "mine_ore_sorting_deck",
    family: "quality",
    displayName: "Ore Sorting Deck",
    shortDescription: "Mechanised grading dramatically improves delivered ore quality.",
    immersiveLabel: "Install a vibrating screen and hand-sorting belt to separate waste rock from ore at the shaft head.",
    projectCategory: "equipment",
    appliesTo: ["mine"],
    effectKind: "flat_quality",
    baseCost: 12000,
    costMultiplier: 1.40,
    baseEffect: 8,
    gainMultiplier: 1.1,
    installTimeMinutes: 480,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "ore_quality", minLevel: 3 }],
  },

  mine_shaft_deepening: {
    key: "mine_shaft_deepening",
    family: "extraction",
    displayName: "Deep Shaft Extension",
    shortDescription: "Sink shafts to virgin ore horizons with massive yield.",
    immersiveLabel: "Drive a new deep incline, install winding gear, and open the lower ore horizon.",
    projectCategory: "facility",
    appliesTo: ["mine"],
    effectKind: "multiplier",
    baseCost: 35000,
    costMultiplier: 1.50,
    baseEffect: 1.30,
    gainMultiplier: 1.08,
    installTimeMinutes: 2880,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "mine_ventilation_system", minLevel: 1 }],
  },

  mine_open_pit_conversion: {
    key: "mine_open_pit_conversion",
    family: "extraction",
    displayName: "Open-Pit Conversion",
    shortDescription: "Transition to surface strip mining for enormous volume.",
    immersiveLabel: "Blast overburden, bring in excavators and haul trucks, and operate the pit at industrial scale.",
    projectCategory: "facility",
    appliesTo: ["mine"],
    effectKind: "multiplier",
    baseCost: 150000,
    costMultiplier: 1.0,
    baseEffect: 1.80,
    gainMultiplier: 1.0,
    installTimeMinutes: 7200,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "mine_shaft_deepening", minLevel: 2 }],
    mutuallyExclusiveWith: ["mine_refined_tunneling"],
    isSpecialization: true,
  },

  mine_refined_tunneling: {
    key: "mine_refined_tunneling",
    family: "quality",
    displayName: "Precision Tunneling",
    shortDescription: "Surgical selective mining maximises grade, not tonnage.",
    immersiveLabel: "Bring in precision drilling rigs and grade-control geologists to mine only the richest pockets.",
    projectCategory: "equipment",
    appliesTo: ["mine"],
    effectKind: "flat_quality",
    baseCost: 150000,
    costMultiplier: 1.0,
    baseEffect: 25,
    gainMultiplier: 1.0,
    installTimeMinutes: 7200,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "mine_ore_sorting_deck", minLevel: 2 }],
    mutuallyExclusiveWith: ["mine_open_pit_conversion"],
    isSpecialization: true,
  },

  // ─── FARM ───────────────────────────────────────────────────────────────────

  farm_seed_stock: {
    key: "farm_seed_stock",
    family: "extraction",
    displayName: "Heirloom Seed Stock",
    shortDescription: "Higher-yielding seed varieties lift every harvest.",
    immersiveLabel: "Source certified seed stock bred for your soil type and growing season.",
    projectCategory: "systems",
    appliesTo: ["farm"],
    effectKind: "multiplier",
    baseCost: 350,
    costMultiplier: 1.30,
    baseEffect: 1.08,
    gainMultiplier: 1.04,
    installTimeMinutes: 20,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  farm_compost_system: {
    key: "farm_compost_system",
    family: "durability",
    displayName: "Compost System",
    shortDescription: "On-site composting reduces purchased inputs.",
    immersiveLabel: "Build covered compost bays and a turning schedule to produce rich on-site fertiliser.",
    projectCategory: "systems",
    appliesTo: ["farm"],
    effectKind: "reduction_multiplier",
    baseCost: 500,
    costMultiplier: 1.32,
    baseEffect: 0.93,
    gainMultiplier: 1.07,
    installTimeMinutes: 45,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_down",
    effectLabel: "Water use multiplier",
  },

  farm_drip_irrigation: {
    key: "farm_drip_irrigation",
    family: "extraction",
    displayName: "Drip Irrigation",
    shortDescription: "Precision water delivery lifts yield and cuts waste.",
    immersiveLabel: "Lay subsurface drip lines fed by a pressure-regulated header tank.",
    projectCategory: "facility",
    appliesTo: ["farm"],
    effectKind: "multiplier",
    baseCost: 4000,
    costMultiplier: 1.38,
    baseEffect: 1.12,
    gainMultiplier: 1.05,
    installTimeMinutes: 300,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "water_efficiency", minLevel: 2 }],
  },

  farm_grain_silo: {
    key: "farm_grain_silo",
    family: "capacity",
    displayName: "Grain Silo",
    shortDescription: "On-site storage lets you hold more harvest at once.",
    immersiveLabel: "Erect a corrugated steel silo with an auger loader and ventilation floor.",
    projectCategory: "facility",
    appliesTo: ["farm"],
    effectKind: "flat_slots",
    baseCost: 6000,
    costMultiplier: 1.40,
    baseEffect: 1,
    gainMultiplier: 1.0,
    installTimeMinutes: 360,
    downtimePolicy: "none",
    stage: "mid",
    maxLevel: 4,
    isInfinite: false,
    uiFormat: "flat_integer",
    effectLabel: "Additional worker slots",
    prerequisites: [{ upgradeKey: "farm_seed_stock", minLevel: 2 }],
  },

  farm_greenhouse: {
    key: "farm_greenhouse",
    family: "extraction",
    displayName: "Greenhouse Bay",
    shortDescription: "Climate control extends the growing season significantly.",
    immersiveLabel: "Frame and glaze a production greenhouse with automated vents and shade cloth.",
    projectCategory: "facility",
    appliesTo: ["farm"],
    effectKind: "multiplier",
    baseCost: 25000,
    costMultiplier: 1.48,
    baseEffect: 1.25,
    gainMultiplier: 1.07,
    installTimeMinutes: 1440,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "farm_drip_irrigation", minLevel: 1 }],
  },

  farm_combine_harvester: {
    key: "farm_combine_harvester",
    family: "extraction",
    displayName: "Combine Harvester",
    shortDescription: "Mechanised harvesting replaces hand labour with machine throughput.",
    immersiveLabel: "Lease or purchase a full combine with header, cab, and grain tank for the main harvest.",
    projectCategory: "equipment",
    appliesTo: ["farm"],
    effectKind: "multiplier",
    baseCost: 45000,
    costMultiplier: 1.50,
    baseEffect: 1.35,
    gainMultiplier: 1.08,
    installTimeMinutes: 2880,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "worker_capacity", minLevel: 3 }],
  },

  farm_organic_certification: {
    key: "farm_organic_certification",
    family: "quality",
    displayName: "Organic Certification",
    shortDescription: "Certified-organic status commands a significant quality premium.",
    immersiveLabel: "Engage a certifying body, convert all inputs to organic, and document three years of compliance.",
    projectCategory: "systems",
    appliesTo: ["farm"],
    effectKind: "flat_quality",
    baseCost: 90000,
    costMultiplier: 1.0,
    baseEffect: 22,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "partial",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "farm_greenhouse", minLevel: 1 }],
    mutuallyExclusiveWith: ["farm_industrial_scale"],
    isSpecialization: true,
  },

  farm_industrial_scale: {
    key: "farm_industrial_scale",
    family: "extraction",
    displayName: "Industrial Farming",
    shortDescription: "Full mechanisation and agrochemicals maximise raw volume.",
    immersiveLabel: "Install precision ag systems, bulk sprayers, and automated soil sensors across every field.",
    projectCategory: "facility",
    appliesTo: ["farm"],
    effectKind: "multiplier",
    baseCost: 90000,
    costMultiplier: 1.0,
    baseEffect: 1.70,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "farm_combine_harvester", minLevel: 1 }],
    mutuallyExclusiveWith: ["farm_organic_certification"],
    isSpecialization: true,
  },

  // ─── LOGGING CAMP ───────────────────────────────────────────────────────────

  logging_chainsaw_fleet: {
    key: "logging_chainsaw_fleet",
    family: "extraction",
    displayName: "Chainsaw Fleet",
    shortDescription: "Professional saws replace axes and bowsaws.",
    immersiveLabel: "Equip every faller with a pro-grade chainsaw and a sharpening schedule.",
    projectCategory: "equipment",
    appliesTo: ["logging_camp"],
    effectKind: "multiplier",
    baseCost: 700,
    costMultiplier: 1.32,
    baseEffect: 1.10,
    gainMultiplier: 1.04,
    installTimeMinutes: 30,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  logging_skid_road: {
    key: "logging_skid_road",
    family: "durability",
    displayName: "Skid Road Grading",
    shortDescription: "A proper haul road reduces equipment wear on every run.",
    immersiveLabel: "Grade and gravel a skid road from the cut to the landing, then ditch the sides.",
    projectCategory: "facility",
    appliesTo: ["logging_camp"],
    effectKind: "multiplier",
    baseCost: 900,
    costMultiplier: 1.33,
    baseEffect: 1.12,
    gainMultiplier: 1.04,
    installTimeMinutes: 60,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Tool durability multiplier",
  },

  logging_loader_crane: {
    key: "logging_loader_crane",
    family: "extraction",
    displayName: "Loader Crane",
    shortDescription: "Mechanised log loading cuts cycle time dramatically.",
    immersiveLabel: "Mount a knuckle-boom crane on the skidder to swing full stems onto the truck.",
    projectCategory: "equipment",
    appliesTo: ["logging_camp"],
    effectKind: "multiplier",
    baseCost: 5500,
    costMultiplier: 1.40,
    baseEffect: 1.15,
    gainMultiplier: 1.05,
    installTimeMinutes: 240,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "logging_chainsaw_fleet", minLevel: 2 }],
  },

  logging_reforestation: {
    key: "logging_reforestation",
    family: "extraction",
    displayName: "Reforestation Program",
    shortDescription: "Managed replanting keeps cut areas productive long-term.",
    immersiveLabel: "Hire a planting crew, source seedlings, and track stocking density by block.",
    projectCategory: "systems",
    appliesTo: ["logging_camp"],
    effectKind: "multiplier",
    baseCost: 4000,
    costMultiplier: 1.38,
    baseEffect: 1.10,
    gainMultiplier: 1.04,
    installTimeMinutes: 180,
    downtimePolicy: "none",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "worker_capacity", minLevel: 2 }],
  },

  logging_bunkhouse: {
    key: "logging_bunkhouse",
    family: "capacity",
    displayName: "Bunkhouse Expansion",
    shortDescription: "On-site accommodation supports a larger permanent crew.",
    immersiveLabel: "Build a bunkhouse and cook shack so crews can work extended rotations.",
    projectCategory: "facility",
    appliesTo: ["logging_camp"],
    effectKind: "flat_slots",
    baseCost: 18000,
    costMultiplier: 1.45,
    baseEffect: 1,
    gainMultiplier: 1.0,
    installTimeMinutes: 960,
    downtimePolicy: "none",
    stage: "late",
    maxLevel: 3,
    isInfinite: false,
    uiFormat: "flat_integer",
    effectLabel: "Additional worker slots",
    prerequisites: [{ upgradeKey: "logging_loader_crane", minLevel: 1 }],
  },

  logging_log_processor: {
    key: "logging_log_processor",
    family: "quality",
    displayName: "Log Processor",
    shortDescription: "On-site processing improves delivered log grade.",
    immersiveLabel: "Station a harvester head at the landing to delimb, buck, and sort stems by grade on the spot.",
    projectCategory: "equipment",
    appliesTo: ["logging_camp"],
    effectKind: "flat_quality",
    baseCost: 22000,
    costMultiplier: 1.45,
    baseEffect: 7,
    gainMultiplier: 1.1,
    installTimeMinutes: 720,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "tool_durability", minLevel: 3 }],
  },

  logging_sustainable_cert: {
    key: "logging_sustainable_cert",
    family: "quality",
    displayName: "Sustainable Forestry Cert",
    shortDescription: "Third-party certification opens premium timber markets.",
    immersiveLabel: "Achieve FSC or equivalent certification through audit, chain-of-custody tracking, and approved prescriptions.",
    projectCategory: "systems",
    appliesTo: ["logging_camp"],
    effectKind: "flat_quality",
    baseCost: 110000,
    costMultiplier: 1.0,
    baseEffect: 20,
    gainMultiplier: 1.0,
    installTimeMinutes: 5040,
    downtimePolicy: "partial",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "logging_log_processor", minLevel: 1 }],
    mutuallyExclusiveWith: ["logging_clear_cut"],
    isSpecialization: true,
  },

  logging_clear_cut: {
    key: "logging_clear_cut",
    family: "extraction",
    displayName: "Clear-Cut Rotation",
    shortDescription: "Industrial clear-felling delivers maximum raw log volume.",
    immersiveLabel: "Bring in feller-bunchers and grapple skidders to clear full blocks on a tight rotation schedule.",
    projectCategory: "equipment",
    appliesTo: ["logging_camp"],
    effectKind: "multiplier",
    baseCost: 110000,
    costMultiplier: 1.0,
    baseEffect: 1.75,
    gainMultiplier: 1.0,
    installTimeMinutes: 5040,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "logging_loader_crane", minLevel: 2 }],
    mutuallyExclusiveWith: ["logging_sustainable_cert"],
    isSpecialization: true,
  },

  // ─── OIL WELL ───────────────────────────────────────────────────────────────

  oil_pump_jack: {
    key: "oil_pump_jack",
    family: "extraction",
    displayName: "Pump Jack Install",
    shortDescription: "Replace the hand pump with a mechanical pump jack.",
    immersiveLabel: "Set a surface pump jack on the wellhead with a counterbalanced walking beam.",
    projectCategory: "equipment",
    appliesTo: ["oil_well"],
    effectKind: "multiplier",
    baseCost: 800,
    costMultiplier: 1.33,
    baseEffect: 1.12,
    gainMultiplier: 1.05,
    installTimeMinutes: 60,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  oil_separator_tank: {
    key: "oil_separator_tank",
    family: "quality",
    displayName: "Separator Tank",
    shortDescription: "Basic crude-water separation improves delivered oil grade.",
    immersiveLabel: "Install a three-phase separator to remove gas, water, and solids from produced fluids.",
    projectCategory: "equipment",
    appliesTo: ["oil_well"],
    effectKind: "flat_quality",
    baseCost: 1200,
    costMultiplier: 1.35,
    baseEffect: 4,
    gainMultiplier: 1.1,
    installTimeMinutes: 90,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  oil_secondary_recovery: {
    key: "oil_secondary_recovery",
    family: "extraction",
    displayName: "Secondary Recovery",
    shortDescription: "Water-flood injection pressurises the reservoir and lifts yield.",
    immersiveLabel: "Drill injection wells and install surface pumps to push formation water into the reservoir.",
    projectCategory: "systems",
    appliesTo: ["oil_well"],
    effectKind: "multiplier",
    baseCost: 6000,
    costMultiplier: 1.42,
    baseEffect: 1.18,
    gainMultiplier: 1.05,
    installTimeMinutes: 360,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "oil_pump_jack", minLevel: 2 }],
  },

  oil_pipeline_connection: {
    key: "oil_pipeline_connection",
    family: "extraction",
    displayName: "Pipeline Connection",
    shortDescription: "Replace truck haulage with a direct pipeline run.",
    immersiveLabel: "Survey, permit, and lay a trunk line from the well pad to the nearest gathering point.",
    projectCategory: "facility",
    appliesTo: ["oil_well"],
    effectKind: "multiplier",
    baseCost: 9000,
    costMultiplier: 1.42,
    baseEffect: 1.12,
    gainMultiplier: 1.04,
    installTimeMinutes: 480,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "extraction_efficiency", minLevel: 2 }],
  },

  oil_tertiary_recovery: {
    key: "oil_tertiary_recovery",
    family: "extraction",
    displayName: "Tertiary Recovery (EOR)",
    shortDescription: "Chemical or thermal injection squeezes maximum oil from the formation.",
    immersiveLabel: "Design and inject a polymer or steam EOR programme with continuous monitoring.",
    projectCategory: "systems",
    appliesTo: ["oil_well"],
    effectKind: "multiplier",
    baseCost: 40000,
    costMultiplier: 1.52,
    baseEffect: 1.30,
    gainMultiplier: 1.08,
    installTimeMinutes: 2880,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "oil_secondary_recovery", minLevel: 1 }],
  },

  oil_refinery_stub: {
    key: "oil_refinery_stub",
    family: "quality",
    displayName: "On-Site Refinery Stub",
    shortDescription: "Partial refining at the wellhead raises value per barrel.",
    immersiveLabel: "Install a skid-mounted atmospheric distillation unit to strip light ends on site.",
    projectCategory: "equipment",
    appliesTo: ["oil_well"],
    effectKind: "flat_quality",
    baseCost: 30000,
    costMultiplier: 1.48,
    baseEffect: 10,
    gainMultiplier: 1.1,
    installTimeMinutes: 1440,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "oil_separator_tank", minLevel: 2 }],
  },

  oil_scada_automation: {
    key: "oil_scada_automation",
    family: "extraction",
    displayName: "SCADA Automation",
    shortDescription: "Automated monitoring and valve control maximises uptime per worker.",
    immersiveLabel: "Deploy a SCADA network with RTUs on every wellhead and a central control room.",
    projectCategory: "systems",
    appliesTo: ["oil_well"],
    effectKind: "multiplier",
    baseCost: 175000,
    costMultiplier: 1.0,
    baseEffect: 1.65,
    gainMultiplier: 1.0,
    installTimeMinutes: 7200,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "oil_tertiary_recovery", minLevel: 1 }],
    mutuallyExclusiveWith: ["oil_manual_optimization"],
    isSpecialization: true,
  },

  oil_manual_optimization: {
    key: "oil_manual_optimization",
    family: "quality",
    displayName: "Expert Well Management",
    shortDescription: "A dedicated petroleum engineer extracts maximum quality per barrel.",
    immersiveLabel: "Hire a resident reservoir engineer to hand-tune chokes, pressures, and drawdown rates daily.",
    projectCategory: "staffing",
    appliesTo: ["oil_well"],
    effectKind: "flat_quality",
    baseCost: 175000,
    costMultiplier: 1.0,
    baseEffect: 22,
    gainMultiplier: 1.0,
    installTimeMinutes: 7200,
    downtimePolicy: "none",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "oil_refinery_stub", minLevel: 1 }],
    mutuallyExclusiveWith: ["oil_scada_automation"],
    isSpecialization: true,
  },

  // ─── WATER COMPANY ──────────────────────────────────────────────────────────

  water_filter_upgrade: {
    key: "water_filter_upgrade",
    family: "quality",
    displayName: "Filtration Upgrade",
    shortDescription: "Better filter media raises delivered water quality.",
    immersiveLabel: "Replace sand beds with activated carbon and membrane cartridges in the filter house.",
    projectCategory: "equipment",
    appliesTo: ["water_company"],
    effectKind: "flat_quality",
    baseCost: 600,
    costMultiplier: 1.33,
    baseEffect: 4,
    gainMultiplier: 1.1,
    installTimeMinutes: 45,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  water_pressure_system: {
    key: "water_pressure_system",
    family: "extraction",
    displayName: "Pressure System Upgrade",
    shortDescription: "Higher line pressure improves delivery rate.",
    immersiveLabel: "Replace ageing pumps with variable-speed drives and upsized header mains.",
    projectCategory: "equipment",
    appliesTo: ["water_company"],
    effectKind: "multiplier",
    baseCost: 800,
    costMultiplier: 1.33,
    baseEffect: 1.10,
    gainMultiplier: 1.04,
    installTimeMinutes: 60,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  water_reservoir_expansion: {
    key: "water_reservoir_expansion",
    family: "extraction",
    displayName: "Reservoir Expansion",
    shortDescription: "More storage means a stable supply through dry periods.",
    immersiveLabel: "Excavate and line a second storage basin, then connect it to the existing treatment train.",
    projectCategory: "facility",
    appliesTo: ["water_company"],
    effectKind: "multiplier",
    baseCost: 7000,
    costMultiplier: 1.40,
    baseEffect: 1.15,
    gainMultiplier: 1.05,
    installTimeMinutes: 360,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "water_pressure_system", minLevel: 2 }],
  },

  water_treatment_plant: {
    key: "water_treatment_plant",
    family: "quality",
    displayName: "Advanced Treatment Plant",
    shortDescription: "Full chemical treatment opens premium distribution contracts.",
    immersiveLabel: "Build a coagulation-flocculation-sedimentation train with UV disinfection and pH dosing.",
    projectCategory: "facility",
    appliesTo: ["water_company"],
    effectKind: "flat_quality",
    baseCost: 28000,
    costMultiplier: 1.48,
    baseEffect: 12,
    gainMultiplier: 1.1,
    installTimeMinutes: 1440,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "water_filter_upgrade", minLevel: 3 }],
  },

  water_distribution_network: {
    key: "water_distribution_network",
    family: "extraction",
    displayName: "Distribution Network",
    shortDescription: "A wider pipe network reaches more customers per cycle.",
    immersiveLabel: "Extend trunk mains into new service zones and install district meter areas.",
    projectCategory: "facility",
    appliesTo: ["water_company"],
    effectKind: "multiplier",
    baseCost: 32000,
    costMultiplier: 1.50,
    baseEffect: 1.28,
    gainMultiplier: 1.07,
    installTimeMinutes: 1440,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "water_reservoir_expansion", minLevel: 1 }],
  },

  water_automated_monitoring: {
    key: "water_automated_monitoring",
    family: "extraction",
    displayName: "Automated Monitoring",
    shortDescription: "SCADA and telemetry keep every pipe at peak efficiency.",
    immersiveLabel: "Fit the network with flow meters, pressure transducers, and a real-time control room.",
    projectCategory: "systems",
    appliesTo: ["water_company"],
    effectKind: "multiplier",
    baseCost: 130000,
    costMultiplier: 1.0,
    baseEffect: 1.60,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "water_distribution_network", minLevel: 1 }],
    mutuallyExclusiveWith: ["water_community_focus"],
    isSpecialization: true,
  },

  water_community_focus: {
    key: "water_community_focus",
    family: "quality",
    displayName: "Community Water Programme",
    shortDescription: "Public trust and local partnerships unlock premium quality contracts.",
    immersiveLabel: "Launch a community liaison programme, publish annual quality reports, and sponsor local water safety.",
    projectCategory: "staffing",
    appliesTo: ["water_company"],
    effectKind: "flat_quality",
    baseCost: 130000,
    costMultiplier: 1.0,
    baseEffect: 20,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "none",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "water_treatment_plant", minLevel: 1 }],
    mutuallyExclusiveWith: ["water_automated_monitoring"],
    isSpecialization: true,
  },

  // ─── SAWMILL ────────────────────────────────────────────────────────────────

  sawmill_blade_set: {
    key: "sawmill_blade_set",
    family: "quality",
    displayName: "Carbide Blade Set",
    shortDescription: "Sharper, longer-lasting blades cut cleaner boards.",
    immersiveLabel: "Fit all head rigs with carbide-tipped blades and a diamond-wheel sharpening station.",
    projectCategory: "equipment",
    appliesTo: ["sawmill"],
    effectKind: "flat_quality",
    baseCost: 700,
    costMultiplier: 1.32,
    baseEffect: 4,
    gainMultiplier: 1.1,
    installTimeMinutes: 30,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  sawmill_log_deck: {
    key: "sawmill_log_deck",
    family: "manufacturing",
    displayName: "Log Deck Automation",
    shortDescription: "Auto-feed moves logs to the saw without manual handling.",
    immersiveLabel: "Install a powered log deck with a kicker mechanism to feed the head saw continuously.",
    projectCategory: "equipment",
    appliesTo: ["sawmill"],
    effectKind: "multiplier",
    baseCost: 900,
    costMultiplier: 1.33,
    baseEffect: 1.10,
    gainMultiplier: 1.04,
    installTimeMinutes: 60,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  sawmill_kiln_dryer: {
    key: "sawmill_kiln_dryer",
    family: "quality",
    displayName: "Kiln Dryer",
    shortDescription: "Kilning lumber on-site removes moisture and opens premium markets.",
    immersiveLabel: "Build a forced-air or steam kiln with a digital control system for precise drying schedules.",
    projectCategory: "facility",
    appliesTo: ["sawmill"],
    effectKind: "flat_quality",
    baseCost: 6000,
    costMultiplier: 1.40,
    baseEffect: 7,
    gainMultiplier: 1.1,
    installTimeMinutes: 360,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "sawmill_blade_set", minLevel: 2 }],
  },

  sawmill_planer_mill: {
    key: "sawmill_planer_mill",
    family: "manufacturing",
    displayName: "Planer Mill Addition",
    shortDescription: "A finishing planer dresses boards and improves throughput.",
    immersiveLabel: "Install a four-sided planer at the outfeed of the head rig to dress and grade in one pass.",
    projectCategory: "equipment",
    appliesTo: ["sawmill"],
    effectKind: "multiplier",
    baseCost: 7500,
    costMultiplier: 1.40,
    baseEffect: 1.15,
    gainMultiplier: 1.05,
    installTimeMinutes: 300,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "sawmill_log_deck", minLevel: 2 }],
  },

  sawmill_waste_boiler: {
    key: "sawmill_waste_boiler",
    family: "manufacturing",
    displayName: "Waste-Wood Boiler",
    shortDescription: "Burn off-cuts and sawdust to generate process heat, cutting operating costs.",
    immersiveLabel: "Install a biomass boiler fed by the chip conveyor to recover energy from all mill waste.",
    projectCategory: "systems",
    appliesTo: ["sawmill"],
    effectKind: "reduction_multiplier",
    baseCost: 20000,
    costMultiplier: 1.45,
    baseEffect: 0.90,
    gainMultiplier: 1.06,
    installTimeMinutes: 960,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_down",
    effectLabel: "Input use multiplier",
    prerequisites: [{ upgradeKey: "sawmill_kiln_dryer", minLevel: 1 }],
  },

  sawmill_cnc_router: {
    key: "sawmill_cnc_router",
    family: "manufacturing",
    displayName: "CNC Router Table",
    shortDescription: "Precision CNC routing unlocks complex cut-to-order products.",
    immersiveLabel: "Commission a large-format CNC router with vacuum hold-down and automatic tool change.",
    projectCategory: "equipment",
    appliesTo: ["sawmill"],
    effectKind: "multiplier",
    baseCost: 38000,
    costMultiplier: 1.50,
    baseEffect: 1.28,
    gainMultiplier: 1.07,
    installTimeMinutes: 2880,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "equipment_quality", minLevel: 3 }],
  },

  sawmill_mass_production: {
    key: "sawmill_mass_production",
    family: "manufacturing",
    displayName: "High-Volume Mill",
    shortDescription: "Fully automated infeed and outfeed for maximum throughput.",
    immersiveLabel: "Convert to a full production-line layout with automated log turning, tagging, and sortation.",
    projectCategory: "facility",
    appliesTo: ["sawmill"],
    effectKind: "multiplier",
    baseCost: 120000,
    costMultiplier: 1.0,
    baseEffect: 1.70,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "sawmill_cnc_router", minLevel: 1 }],
    mutuallyExclusiveWith: ["sawmill_premium_lumber"],
    isSpecialization: true,
  },

  sawmill_premium_lumber: {
    key: "sawmill_premium_lumber",
    family: "quality",
    displayName: "Fine Lumber Operation",
    shortDescription: "Slow, exacting production yields the highest-grade timber in the market.",
    immersiveLabel: "Dedicate the mill to air-dried, hand-graded, FSC-certified premium cuts only.",
    projectCategory: "systems",
    appliesTo: ["sawmill"],
    effectKind: "flat_quality",
    baseCost: 120000,
    costMultiplier: 1.0,
    baseEffect: 22,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "sawmill_kiln_dryer", minLevel: 2 }],
    mutuallyExclusiveWith: ["sawmill_mass_production"],
    isSpecialization: true,
  },

  // ─── METALWORKING FACTORY ───────────────────────────────────────────────────

  metal_forge_lining: {
    key: "metal_forge_lining",
    family: "manufacturing",
    displayName: "Refractory Lining",
    shortDescription: "Insulated forge walls retain heat, slashing fuel use.",
    immersiveLabel: "Reline the forge chamber with high-alumina brick and a castable backup layer.",
    projectCategory: "equipment",
    appliesTo: ["metalworking_factory"],
    effectKind: "reduction_multiplier",
    baseCost: 900,
    costMultiplier: 1.33,
    baseEffect: 0.92,
    gainMultiplier: 1.07,
    installTimeMinutes: 60,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_down",
    effectLabel: "Input use multiplier",
  },

  metal_grinder_rack: {
    key: "metal_grinder_rack",
    family: "quality",
    displayName: "Precision Grinder Rack",
    shortDescription: "A dedicated grinding station improves surface finish on every part.",
    immersiveLabel: "Install a surface grinder and deburring belt adjacent to the finishing bench.",
    projectCategory: "equipment",
    appliesTo: ["metalworking_factory"],
    effectKind: "flat_quality",
    baseCost: 1100,
    costMultiplier: 1.33,
    baseEffect: 4,
    gainMultiplier: 1.1,
    installTimeMinutes: 45,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  metal_induction_furnace: {
    key: "metal_induction_furnace",
    family: "manufacturing",
    displayName: "Induction Furnace",
    shortDescription: "Electric induction heating cuts cycle time and fuel cost.",
    immersiveLabel: "Commission a medium-frequency induction furnace with a matched power supply unit.",
    projectCategory: "equipment",
    appliesTo: ["metalworking_factory"],
    effectKind: "multiplier",
    baseCost: 7500,
    costMultiplier: 1.42,
    baseEffect: 1.15,
    gainMultiplier: 1.05,
    installTimeMinutes: 360,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "metal_forge_lining", minLevel: 2 }],
  },

  metal_cnc_lathe: {
    key: "metal_cnc_lathe",
    family: "quality",
    displayName: "CNC Lathe",
    shortDescription: "Automated turning delivers tight tolerances and consistent finish.",
    immersiveLabel: "Install a two-axis CNC turning centre with a live tooling turret and bar feeder.",
    projectCategory: "equipment",
    appliesTo: ["metalworking_factory"],
    effectKind: "flat_quality",
    baseCost: 9000,
    costMultiplier: 1.42,
    baseEffect: 7,
    gainMultiplier: 1.1,
    installTimeMinutes: 480,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "equipment_quality", minLevel: 2 }],
  },

  metal_heat_treatment_oven: {
    key: "metal_heat_treatment_oven",
    family: "quality",
    displayName: "Heat Treatment Oven",
    shortDescription: "Controlled tempering produces harder, more durable finished parts.",
    immersiveLabel: "Install a batch heat-treatment furnace with programmable cycles and quench tank.",
    projectCategory: "equipment",
    appliesTo: ["metalworking_factory"],
    effectKind: "flat_quality",
    baseCost: 28000,
    costMultiplier: 1.48,
    baseEffect: 10,
    gainMultiplier: 1.1,
    installTimeMinutes: 1440,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "metal_cnc_lathe", minLevel: 1 }],
  },

  metal_robotic_welder: {
    key: "metal_robotic_welder",
    family: "manufacturing",
    displayName: "Robotic Welding Arm",
    shortDescription: "An articulated robot welds faster and more consistently than any hand.",
    immersiveLabel: "Integrate a six-axis welding robot with a positioner jig and fume extraction.",
    projectCategory: "equipment",
    appliesTo: ["metalworking_factory"],
    effectKind: "multiplier",
    baseCost: 42000,
    costMultiplier: 1.50,
    baseEffect: 1.32,
    gainMultiplier: 1.08,
    installTimeMinutes: 2880,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [
      { upgradeKey: "worker_capacity", minLevel: 3 },
      { upgradeKey: "metal_induction_furnace", minLevel: 1 },
    ],
  },

  metal_specialty_alloys: {
    key: "metal_specialty_alloys",
    family: "quality",
    displayName: "Specialty Alloy Line",
    shortDescription: "Rare alloy metallurgy commands the highest prices in the market.",
    immersiveLabel: "Establish a dedicated alloy kitchen with a vacuum induction melter and spectrometer.",
    projectCategory: "equipment",
    appliesTo: ["metalworking_factory"],
    effectKind: "flat_quality",
    baseCost: 200000,
    costMultiplier: 1.0,
    baseEffect: 25,
    gainMultiplier: 1.0,
    installTimeMinutes: 8640,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "metal_heat_treatment_oven", minLevel: 1 }],
    mutuallyExclusiveWith: ["metal_mass_stampings"],
    isSpecialization: true,
  },

  metal_mass_stampings: {
    key: "metal_mass_stampings",
    family: "manufacturing",
    displayName: "Stamping Press Line",
    shortDescription: "High-speed progressive stamping delivers maximum parts per hour.",
    immersiveLabel: "Commission a progressive die stamping line with coil feed, straightener, and auto-stacker.",
    projectCategory: "facility",
    appliesTo: ["metalworking_factory"],
    effectKind: "multiplier",
    baseCost: 200000,
    costMultiplier: 1.0,
    baseEffect: 1.80,
    gainMultiplier: 1.0,
    installTimeMinutes: 8640,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "metal_robotic_welder", minLevel: 1 }],
    mutuallyExclusiveWith: ["metal_specialty_alloys"],
    isSpecialization: true,
  },

  // ─── FOOD PROCESSING PLANT ──────────────────────────────────────────────────

  food_cold_storage: {
    key: "food_cold_storage",
    family: "manufacturing",
    displayName: "Cold Storage Unit",
    shortDescription: "Refrigerated storage dramatically cuts raw-material spoilage.",
    immersiveLabel: "Install walk-in cool rooms and a refrigerated receiving dock with temperature logging.",
    projectCategory: "facility",
    appliesTo: ["food_processing_plant"],
    effectKind: "reduction_multiplier",
    baseCost: 800,
    costMultiplier: 1.33,
    baseEffect: 0.91,
    gainMultiplier: 1.07,
    installTimeMinutes: 60,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_down",
    effectLabel: "Input use multiplier",
  },

  food_pasteurizer: {
    key: "food_pasteurizer",
    family: "quality",
    displayName: "Pasteuriser",
    shortDescription: "Heat treatment improves food safety and quality scores.",
    immersiveLabel: "Install a plate heat exchanger pasteuriser with automated hold-tube and CIP system.",
    projectCategory: "equipment",
    appliesTo: ["food_processing_plant"],
    effectKind: "flat_quality",
    baseCost: 1100,
    costMultiplier: 1.33,
    baseEffect: 5,
    gainMultiplier: 1.1,
    installTimeMinutes: 90,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  food_packaging_line: {
    key: "food_packaging_line",
    family: "manufacturing",
    displayName: "Packaging Line",
    shortDescription: "Automated fill-seal packaging lifts throughput significantly.",
    immersiveLabel: "Commission a form-fill-seal line with a checkweigher, date coder, and case erector.",
    projectCategory: "equipment",
    appliesTo: ["food_processing_plant"],
    effectKind: "multiplier",
    baseCost: 6500,
    costMultiplier: 1.40,
    baseEffect: 1.15,
    gainMultiplier: 1.05,
    installTimeMinutes: 300,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "food_cold_storage", minLevel: 2 }],
  },

  food_batch_cooker: {
    key: "food_batch_cooker",
    family: "manufacturing",
    displayName: "Industrial Batch Cooker",
    shortDescription: "Large jacketed kettles process high volumes in a single cook.",
    immersiveLabel: "Install steam-jacketed batch kettles with agitators, CIP, and automated temperature control.",
    projectCategory: "equipment",
    appliesTo: ["food_processing_plant"],
    effectKind: "multiplier",
    baseCost: 35000,
    costMultiplier: 1.50,
    baseEffect: 1.30,
    gainMultiplier: 1.08,
    installTimeMinutes: 2880,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "food_packaging_line", minLevel: 1 }],
  },

  food_freeze_dryer: {
    key: "food_freeze_dryer",
    family: "quality",
    displayName: "Freeze-Dry Line",
    shortDescription: "Lyophilisation preserves nutrients and delivers a premium shelf-stable product.",
    immersiveLabel: "Install a production-scale freeze-dryer with condenser, vacuum system, and cycle controller.",
    projectCategory: "equipment",
    appliesTo: ["food_processing_plant"],
    effectKind: "flat_quality",
    baseCost: 28000,
    costMultiplier: 1.48,
    baseEffect: 10,
    gainMultiplier: 1.1,
    installTimeMinutes: 1440,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "food_pasteurizer", minLevel: 2 }],
  },

  food_organic_label: {
    key: "food_organic_label",
    family: "quality",
    displayName: "Organic Label Line",
    shortDescription: "Certified-organic production commands a strong price premium.",
    immersiveLabel: "Segregate organic and conventional lines, complete audits, and launch the certified range.",
    projectCategory: "systems",
    appliesTo: ["food_processing_plant"],
    effectKind: "flat_quality",
    baseCost: 120000,
    costMultiplier: 1.0,
    baseEffect: 22,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "partial",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "food_freeze_dryer", minLevel: 1 }],
    mutuallyExclusiveWith: ["food_mass_market"],
    isSpecialization: true,
  },

  food_mass_market: {
    key: "food_mass_market",
    family: "manufacturing",
    displayName: "Mass Market Production",
    shortDescription: "A fully automated line runs around the clock at maximum throughput.",
    immersiveLabel: "Convert to a continuous-flow process with aseptic filling, robotic palletising, and SCADA control.",
    projectCategory: "facility",
    appliesTo: ["food_processing_plant"],
    effectKind: "multiplier",
    baseCost: 120000,
    costMultiplier: 1.0,
    baseEffect: 1.75,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "food_batch_cooker", minLevel: 1 }],
    mutuallyExclusiveWith: ["food_organic_label"],
    isSpecialization: true,
  },

  // ─── WINERY / DISTILLERY ────────────────────────────────────────────────────

  winery_oak_barrels: {
    key: "winery_oak_barrels",
    family: "quality",
    displayName: "Oak Barrel Stock",
    shortDescription: "Ageing in oak lifts complexity and quality measurably.",
    immersiveLabel: "Purchase a first stock of French or American oak barrels and establish a barrel rotation schedule.",
    projectCategory: "equipment",
    appliesTo: ["winery_distillery"],
    effectKind: "flat_quality",
    baseCost: 900,
    costMultiplier: 1.33,
    baseEffect: 5,
    gainMultiplier: 1.1,
    installTimeMinutes: 45,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  winery_grape_press: {
    key: "winery_grape_press",
    family: "manufacturing",
    displayName: "Hydraulic Press",
    shortDescription: "A pneumatic press extracts more juice from every batch.",
    immersiveLabel: "Replace the bladder press with a full pneumatic press chamber and programmable cycles.",
    projectCategory: "equipment",
    appliesTo: ["winery_distillery"],
    effectKind: "multiplier",
    baseCost: 1200,
    costMultiplier: 1.33,
    baseEffect: 1.10,
    gainMultiplier: 1.04,
    installTimeMinutes: 90,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  winery_temperature_tanks: {
    key: "winery_temperature_tanks",
    family: "quality",
    displayName: "Temperature-Controlled Tanks",
    shortDescription: "Precise fermentation temperature eliminates batch variance.",
    immersiveLabel: "Fit jacketed stainless tanks with glycol chillers and digital temperature controllers.",
    projectCategory: "equipment",
    appliesTo: ["winery_distillery"],
    effectKind: "flat_quality",
    baseCost: 7000,
    costMultiplier: 1.40,
    baseEffect: 7,
    gainMultiplier: 1.1,
    installTimeMinutes: 360,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "winery_oak_barrels", minLevel: 2 }],
  },

  winery_bottling_line: {
    key: "winery_bottling_line",
    family: "manufacturing",
    displayName: "Automated Bottling Line",
    shortDescription: "A rinse-fill-cork line eliminates hand-bottling bottlenecks.",
    immersiveLabel: "Install a monoblock bottle rinser, filler, corker, and labeller with a conveyor backbone.",
    projectCategory: "equipment",
    appliesTo: ["winery_distillery"],
    effectKind: "multiplier",
    baseCost: 8500,
    costMultiplier: 1.42,
    baseEffect: 1.15,
    gainMultiplier: 1.05,
    installTimeMinutes: 360,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "winery_grape_press", minLevel: 2 }],
  },

  winery_cellar_expansion: {
    key: "winery_cellar_expansion",
    family: "quality",
    displayName: "Underground Cellar",
    shortDescription: "A deep, temperature-stable cellar ages product to a higher grade.",
    immersiveLabel: "Excavate and line an underground barrel hall with natural ventilation and humidity control.",
    projectCategory: "facility",
    appliesTo: ["winery_distillery"],
    effectKind: "flat_quality",
    baseCost: 35000,
    costMultiplier: 1.50,
    baseEffect: 12,
    gainMultiplier: 1.1,
    installTimeMinutes: 2880,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "winery_temperature_tanks", minLevel: 1 }],
  },

  winery_master_distiller: {
    key: "winery_master_distiller",
    family: "quality",
    displayName: "Master Distiller / Winemaker",
    shortDescription: "An expert nose and palate raises every batch's ceiling.",
    immersiveLabel: "Recruit a credentialed master distiller or winemaker as head of production.",
    projectCategory: "staffing",
    appliesTo: ["winery_distillery"],
    effectKind: "flat_quality",
    baseCost: 28000,
    costMultiplier: 1.48,
    baseEffect: 9,
    gainMultiplier: 1.1,
    installTimeMinutes: 480,
    downtimePolicy: "none",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "equipment_quality", minLevel: 3 }],
  },

  winery_prestige_label: {
    key: "winery_prestige_label",
    family: "store",
    displayName: "Prestige Label",
    shortDescription: "A flagship label builds brand recognition and draws customers.",
    immersiveLabel: "Launch a named prestige range with distinctive packaging, allocated distribution, and press tastings.",
    projectCategory: "storefront",
    appliesTo: ["winery_distillery"],
    effectKind: "traffic_multiplier",
    baseCost: 140000,
    costMultiplier: 1.0,
    baseEffect: 1.45,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "partial",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Traffic multiplier",
    prerequisites: [{ upgradeKey: "winery_cellar_expansion", minLevel: 1 }],
    mutuallyExclusiveWith: ["winery_bulk_distribution"],
    isSpecialization: true,
  },

  winery_bulk_distribution: {
    key: "winery_bulk_distribution",
    family: "manufacturing",
    displayName: "Bulk Distribution Contract",
    shortDescription: "High-volume contracts keep every tank full and flowing.",
    immersiveLabel: "Negotiate national distribution agreements and convert to ISO tank and flexitank bulk shipping.",
    projectCategory: "systems",
    appliesTo: ["winery_distillery"],
    effectKind: "multiplier",
    baseCost: 140000,
    costMultiplier: 1.0,
    baseEffect: 1.70,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "none",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "winery_bottling_line", minLevel: 2 }],
    mutuallyExclusiveWith: ["winery_prestige_label"],
    isSpecialization: true,
  },

  // ─── CARPENTRY WORKSHOP ─────────────────────────────────────────────────────

  carp_hand_tool_set: {
    key: "carp_hand_tool_set",
    family: "quality",
    displayName: "Professional Hand Tool Set",
    shortDescription: "Quality chisels, planes, and saws lift the finish of every piece.",
    immersiveLabel: "Invest in a full set of professional-grade hand tools and a proper sharpening station.",
    projectCategory: "equipment",
    appliesTo: ["carpentry_workshop"],
    effectKind: "flat_quality",
    baseCost: 500,
    costMultiplier: 1.30,
    baseEffect: 4,
    gainMultiplier: 1.1,
    installTimeMinutes: 20,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
  },

  carp_table_saw: {
    key: "carp_table_saw",
    family: "manufacturing",
    displayName: "Cabinet Table Saw",
    shortDescription: "A cabinet saw enables faster, straighter cuts across all stock.",
    immersiveLabel: "Replace the bench saw with a cast-iron cabinet saw and a premium fence system.",
    projectCategory: "equipment",
    appliesTo: ["carpentry_workshop"],
    effectKind: "multiplier",
    baseCost: 700,
    costMultiplier: 1.32,
    baseEffect: 1.10,
    gainMultiplier: 1.04,
    installTimeMinutes: 30,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
  },

  carp_dust_collector: {
    key: "carp_dust_collector",
    family: "manufacturing",
    displayName: "Dust Collection System",
    shortDescription: "Central dust extraction keeps machines clear and reduces waste.",
    immersiveLabel: "Install a central cyclone and bag-house dust collector piped to every machine.",
    projectCategory: "systems",
    appliesTo: ["carpentry_workshop"],
    effectKind: "reduction_multiplier",
    baseCost: 4500,
    costMultiplier: 1.38,
    baseEffect: 0.92,
    gainMultiplier: 1.06,
    installTimeMinutes: 180,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_down",
    effectLabel: "Input use multiplier",
    prerequisites: [{ upgradeKey: "carp_table_saw", minLevel: 2 }],
  },

  carp_spray_booth: {
    key: "carp_spray_booth",
    family: "quality",
    displayName: "Spray Finish Booth",
    shortDescription: "A dedicated spray booth delivers a professional factory-quality finish.",
    immersiveLabel: "Build a downdraught spray booth with filtered exhaust and a curing tunnel.",
    projectCategory: "facility",
    appliesTo: ["carpentry_workshop"],
    effectKind: "flat_quality",
    baseCost: 6500,
    costMultiplier: 1.40,
    baseEffect: 7,
    gainMultiplier: 1.1,
    installTimeMinutes: 300,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "carp_hand_tool_set", minLevel: 2 }],
  },

  carp_panel_saw: {
    key: "carp_panel_saw",
    family: "manufacturing",
    displayName: "Panel Saw",
    shortDescription: "A vertical panel saw processes full sheets at speed.",
    immersiveLabel: "Install a wall-mounted vertical panel saw on a sliding carriage for full-sheet capacity.",
    projectCategory: "equipment",
    appliesTo: ["carpentry_workshop"],
    effectKind: "multiplier",
    baseCost: 22000,
    costMultiplier: 1.45,
    baseEffect: 1.22,
    gainMultiplier: 1.06,
    installTimeMinutes: 720,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "carp_dust_collector", minLevel: 1 }],
  },

  carp_cnc_joinery: {
    key: "carp_cnc_joinery",
    family: "quality",
    displayName: "CNC Joinery Machine",
    shortDescription: "Automated CNC joinery delivers perfect joints at scale.",
    immersiveLabel: "Integrate a 5-axis CNC machining centre with automatic tool changer and vacuum bed.",
    projectCategory: "equipment",
    appliesTo: ["carpentry_workshop"],
    effectKind: "flat_quality",
    baseCost: 40000,
    costMultiplier: 1.50,
    baseEffect: 12,
    gainMultiplier: 1.1,
    installTimeMinutes: 2880,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "equipment_quality", minLevel: 3 }],
  },

  carp_bespoke_workshop: {
    key: "carp_bespoke_workshop",
    family: "quality",
    displayName: "Bespoke Workshop",
    shortDescription: "Dedicated to one-of-a-kind commissions at the highest quality tier.",
    immersiveLabel: "Convert the shop to a by-commission bespoke operation with a showroom and dedicated master craftsman.",
    projectCategory: "facility",
    appliesTo: ["carpentry_workshop"],
    effectKind: "flat_quality",
    baseCost: 130000,
    costMultiplier: 1.0,
    baseEffect: 24,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "quality_points",
    effectLabel: "Quality bonus",
    prerequisites: [{ upgradeKey: "carp_cnc_joinery", minLevel: 1 }],
    mutuallyExclusiveWith: ["carp_production_shop"],
    isSpecialization: true,
  },

  carp_production_shop: {
    key: "carp_production_shop",
    family: "manufacturing",
    displayName: "Production Shop",
    shortDescription: "Fully jig-based production maximises units per shift.",
    immersiveLabel: "Lay out the floor for lean flow, install production jigs, and standardise on three best-selling designs.",
    projectCategory: "facility",
    appliesTo: ["carpentry_workshop"],
    effectKind: "multiplier",
    baseCost: 130000,
    costMultiplier: 1.0,
    baseEffect: 1.75,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Output multiplier",
    prerequisites: [{ upgradeKey: "carp_panel_saw", minLevel: 1 }],
    mutuallyExclusiveWith: ["carp_bespoke_workshop"],
    isSpecialization: true,
  },

  // ─── GENERAL STORE ──────────────────────────────────────────────────────────

  store_window_display: {
    key: "store_window_display",
    family: "store",
    displayName: "Window Display",
    shortDescription: "A well-dressed window draws passing trade into the store.",
    immersiveLabel: "Design and dress a seasonal window display with proper lighting and rotating product features.",
    projectCategory: "storefront",
    appliesTo: ["general_store"],
    effectKind: "traffic_multiplier",
    baseCost: 400,
    costMultiplier: 1.30,
    baseEffect: 1.06,
    gainMultiplier: 1.03,
    installTimeMinutes: 20,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Traffic multiplier",
  },

  store_loyalty_board: {
    key: "store_loyalty_board",
    family: "store",
    displayName: "Loyalty Programme",
    shortDescription: "A simple punch-card system encourages repeat visits.",
    immersiveLabel: "Launch a stamp-card loyalty programme with a small counter display and printed cards.",
    projectCategory: "staffing",
    appliesTo: ["general_store"],
    effectKind: "conversion_multiplier",
    baseCost: 500,
    costMultiplier: 1.30,
    baseEffect: 1.04,
    gainMultiplier: 1.02,
    installTimeMinutes: 15,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Conversion multiplier",
  },

  store_pos_system: {
    key: "store_pos_system",
    family: "store",
    displayName: "POS System",
    shortDescription: "A modern point-of-sale terminal speeds checkout and reduces errors.",
    immersiveLabel: "Install a touchscreen POS with barcode scanner, receipt printer, and integrated stock tracking.",
    projectCategory: "systems",
    appliesTo: ["general_store"],
    effectKind: "conversion_multiplier",
    baseCost: 3500,
    costMultiplier: 1.38,
    baseEffect: 1.06,
    gainMultiplier: 1.03,
    installTimeMinutes: 120,
    downtimePolicy: "none",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Conversion multiplier",
    prerequisites: [{ upgradeKey: "store_loyalty_board", minLevel: 2 }],
  },

  store_stockroom_shelving: {
    key: "store_stockroom_shelving",
    family: "capacity",
    displayName: "Stockroom Shelving",
    shortDescription: "Dense back-of-house storage lets you carry more lines.",
    immersiveLabel: "Fit the stockroom with heavy-duty longspan shelving and a clear FIFO rotation system.",
    projectCategory: "facility",
    appliesTo: ["general_store"],
    effectKind: "flat_slots",
    baseCost: 5000,
    costMultiplier: 1.40,
    baseEffect: 1,
    gainMultiplier: 1.0,
    installTimeMinutes: 240,
    downtimePolicy: "partial",
    stage: "mid",
    maxLevel: 5,
    isInfinite: false,
    uiFormat: "flat_integer",
    effectLabel: "Additional listings",
    prerequisites: [{ upgradeKey: "listing_capacity", minLevel: 3 }],
  },

  store_delivery_van: {
    key: "store_delivery_van",
    family: "store",
    displayName: "Delivery Van",
    shortDescription: "Offering local delivery brings in customers who never walk past.",
    immersiveLabel: "Purchase or lease a branded delivery van and set up an order-and-deliver service.",
    projectCategory: "facility",
    appliesTo: ["general_store"],
    effectKind: "traffic_multiplier",
    baseCost: 20000,
    costMultiplier: 1.45,
    baseEffect: 1.18,
    gainMultiplier: 1.05,
    installTimeMinutes: 720,
    downtimePolicy: "none",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Traffic multiplier",
    prerequisites: [{ upgradeKey: "store_pos_system", minLevel: 1 }],
  },

  store_second_checkout: {
    key: "store_second_checkout",
    family: "store",
    displayName: "Second Checkout Lane",
    shortDescription: "A second till eliminates queues during peak hours.",
    immersiveLabel: "Fit a second full checkout counter with its own POS, scanner, and card reader.",
    projectCategory: "facility",
    appliesTo: ["general_store"],
    effectKind: "conversion_multiplier",
    baseCost: 28000,
    costMultiplier: 1.48,
    baseEffect: 1.15,
    gainMultiplier: 1.06,
    installTimeMinutes: 960,
    downtimePolicy: "partial",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Conversion multiplier",
    prerequisites: [{ upgradeKey: "store_pos_system", minLevel: 2 }],
  },

  store_franchise_model: {
    key: "store_franchise_model",
    family: "store",
    displayName: "Franchise Operations",
    shortDescription: "A franchise-ready model drives traffic through brand recognition.",
    immersiveLabel: "Standardise the store layout, branding, and supplier roster into a replicable franchise manual.",
    projectCategory: "systems",
    appliesTo: ["general_store"],
    effectKind: "traffic_multiplier",
    baseCost: 160000,
    costMultiplier: 1.0,
    baseEffect: 1.50,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "partial",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Traffic multiplier",
    prerequisites: [{ upgradeKey: "store_delivery_van", minLevel: 1 }],
    mutuallyExclusiveWith: ["store_premium_boutique"],
    isSpecialization: true,
  },

  store_premium_boutique: {
    key: "store_premium_boutique",
    family: "store",
    displayName: "Premium Boutique",
    shortDescription: "Curated luxury presentation lets you charge top-tier prices.",
    immersiveLabel: "Redesign the shop as a premium boutique with handpicked lines, premium fixtures, and personal service.",
    projectCategory: "storefront",
    appliesTo: ["general_store"],
    effectKind: "price_tolerance",
    baseCost: 160000,
    costMultiplier: 1.0,
    baseEffect: 1.40,
    gainMultiplier: 1.0,
    installTimeMinutes: 5760,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Price tolerance multiplier",
    prerequisites: [{ upgradeKey: "store_second_checkout", minLevel: 1 }],
    mutuallyExclusiveWith: ["store_franchise_model"],
    isSpecialization: true,
  },

  // ─── SPECIALTY STORE ────────────────────────────────────────────────────────

  spec_expert_staff: {
    key: "spec_expert_staff",
    family: "store",
    displayName: "Expert Staff",
    shortDescription: "Knowledgeable staff dramatically improve conversion on specialist products.",
    immersiveLabel: "Recruit and onboard staff with hands-on expertise in your product category.",
    projectCategory: "staffing",
    appliesTo: ["specialty_store"],
    effectKind: "conversion_multiplier",
    baseCost: 600,
    costMultiplier: 1.32,
    baseEffect: 1.05,
    gainMultiplier: 1.03,
    installTimeMinutes: 30,
    downtimePolicy: "none",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Conversion multiplier",
  },

  spec_display_case: {
    key: "spec_display_case",
    family: "store",
    displayName: "Specialty Display Case",
    shortDescription: "A quality display case showcases premium items and draws attention.",
    immersiveLabel: "Install lit glass display cases with lockable doors and proper product lighting.",
    projectCategory: "storefront",
    appliesTo: ["specialty_store"],
    effectKind: "traffic_multiplier",
    baseCost: 800,
    costMultiplier: 1.33,
    baseEffect: 1.06,
    gainMultiplier: 1.03,
    installTimeMinutes: 45,
    downtimePolicy: "partial",
    stage: "early",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Traffic multiplier",
  },

  spec_private_label: {
    key: "spec_private_label",
    family: "store",
    displayName: "Private Label Line",
    shortDescription: "Own-brand products command higher margins and reinforce identity.",
    immersiveLabel: "Develop a private-label product range with custom packaging sourced through your own suppliers.",
    projectCategory: "systems",
    appliesTo: ["specialty_store"],
    effectKind: "price_tolerance",
    baseCost: 5500,
    costMultiplier: 1.40,
    baseEffect: 1.08,
    gainMultiplier: 1.04,
    installTimeMinutes: 240,
    downtimePolicy: "none",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Price tolerance multiplier",
    prerequisites: [{ upgradeKey: "spec_expert_staff", minLevel: 2 }],
  },

  spec_loyalty_program: {
    key: "spec_loyalty_program",
    family: "store",
    displayName: "Rewards Programme",
    shortDescription: "A tiered rewards programme locks in the best customers.",
    immersiveLabel: "Launch a digital points programme with app-based tracking and tier rewards.",
    projectCategory: "staffing",
    appliesTo: ["specialty_store"],
    effectKind: "conversion_multiplier",
    baseCost: 4500,
    costMultiplier: 1.38,
    baseEffect: 1.06,
    gainMultiplier: 1.03,
    installTimeMinutes: 180,
    downtimePolicy: "none",
    stage: "mid",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Conversion multiplier",
    prerequisites: [{ upgradeKey: "customer_service", minLevel: 2 }],
  },

  spec_event_space: {
    key: "spec_event_space",
    family: "store",
    displayName: "In-Store Event Space",
    shortDescription: "Hosting events drives traffic spikes and builds loyal community.",
    immersiveLabel: "Clear a rear area, fit it with AV and seating, and run weekly product events and demos.",
    projectCategory: "facility",
    appliesTo: ["specialty_store"],
    effectKind: "traffic_multiplier",
    baseCost: 22000,
    costMultiplier: 1.45,
    baseEffect: 1.20,
    gainMultiplier: 1.06,
    installTimeMinutes: 720,
    downtimePolicy: "full",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Traffic multiplier",
    prerequisites: [{ upgradeKey: "storefront_appeal", minLevel: 3 }],
  },

  spec_membership_tier: {
    key: "spec_membership_tier",
    family: "store",
    displayName: "Membership Tier",
    shortDescription: "Paid membership unlocks exclusive access and drives premium conversion.",
    immersiveLabel: "Launch an annual membership programme with exclusive pricing, early access, and a members lounge.",
    projectCategory: "systems",
    appliesTo: ["specialty_store"],
    effectKind: "price_tolerance",
    baseCost: 30000,
    costMultiplier: 1.48,
    baseEffect: 1.18,
    gainMultiplier: 1.06,
    installTimeMinutes: 960,
    downtimePolicy: "none",
    stage: "late",
    maxLevel: null,
    isInfinite: true,
    uiFormat: "percent_up",
    effectLabel: "Price tolerance multiplier",
    prerequisites: [{ upgradeKey: "spec_loyalty_program", minLevel: 1 }],
  },

  spec_exclusive_supplier: {
    key: "spec_exclusive_supplier",
    family: "store",
    displayName: "Exclusive Supplier Contract",
    shortDescription: "Access to rare, hard-to-find inventory draws the most serious buyers.",
    immersiveLabel: "Negotiate an exclusive regional distribution deal with a premium or artisan supplier.",
    projectCategory: "systems",
    appliesTo: ["specialty_store"],
    effectKind: "traffic_multiplier",
    baseCost: 170000,
    costMultiplier: 1.0,
    baseEffect: 1.55,
    gainMultiplier: 1.0,
    installTimeMinutes: 7200,
    downtimePolicy: "partial",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Traffic multiplier",
    prerequisites: [{ upgradeKey: "spec_event_space", minLevel: 1 }],
    mutuallyExclusiveWith: ["spec_flagship_store"],
    isSpecialization: true,
  },

  spec_flagship_store: {
    key: "spec_flagship_store",
    family: "store",
    displayName: "Flagship Store",
    shortDescription: "A prestige flagship commands the best conversion in the market.",
    immersiveLabel: "Undertake a full shopfit to flagship standard: architectural lighting, bespoke fixtures, and a concierge desk.",
    projectCategory: "storefront",
    appliesTo: ["specialty_store"],
    effectKind: "conversion_multiplier",
    baseCost: 170000,
    costMultiplier: 1.0,
    baseEffect: 1.55,
    gainMultiplier: 1.0,
    installTimeMinutes: 7200,
    downtimePolicy: "full",
    stage: "specialization",
    maxLevel: 1,
    isInfinite: false,
    uiFormat: "percent_up",
    effectLabel: "Conversion multiplier",
    prerequisites: [{ upgradeKey: "spec_membership_tier", minLevel: 1 }],
    mutuallyExclusiveWith: ["spec_exclusive_supplier"],
    isSpecialization: true,
  },
};

export function getBusinessUpgradeDefinition(
  key: BusinessUpgradeKey
): BusinessUpgradeDefinition | null {
  return BUSINESS_UPGRADE_DEFINITIONS[key] ?? null;
}

export function getBusinessUpgradeDefinitions(): BusinessUpgradeDefinition[] {
  return BUSINESS_UPGRADE_KEYS.map((key) => BUSINESS_UPGRADE_DEFINITIONS[key]);
}

export function getBusinessUpgradeDefinitionsForBusinessType(
  businessType: BusinessType
): BusinessUpgradeDefinition[] {
  return getBusinessUpgradeDefinitions().filter((definition) =>
    definition.appliesTo.includes(businessType)
  );
}

export function getBusinessUpgradeKeysForBusinessType(
  businessType: BusinessType
): BusinessUpgradeKey[] {
  return getBusinessUpgradeDefinitionsForBusinessType(businessType).map((definition) => definition.key);
}
